spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true 
        show_sql: true   
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgresql:5432/pessoa}
    username: ${DATABASE_USERNAME:pessoa}
    password: ${DATABASE_PASSWORD:pessoa}
    driver-class-name: org.postgresql.Driver