apiVersion: v1
kind: Service
metadata:
  name: meu-service
spec:
  selector:
    app: meu-nginx
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30501

---

apiVersion: v1
kind: Pod
metadata:
  name: meu-pod
  labels:
    app: meu-nginx
spec:
  containers:
    - name: meu-nginx-container
      image: nginx